Jwt client auth
hse-spb-2024-java/MoodActivities pull request #14
Opened 2024-03-12 21:40 UTC by eyakm1

2024-03-13 22:07 UTC, sssi111 requested changes
мне не очень нравится визуал, но пока это всё в стадии dev, то норм
главная проблема, что пока не отображаются проблемы при логине (сеть, пароль, etc)

2024-03-13 22:07 UTC, sssi111 commented on app/src/main/AndroidManifest.xml
> +            android:name=".activities.LoginActivity"
это конечно временное, но надо какой-то экран загрузки, на котором в фоне будет проверка на логин

2024-03-13 22:07 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/activities/RegisterActivity.kt
> +                Log.d("RegistrationResponse", "Passwords do not match")
лог :(

2024-03-13 22:07 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/connection/Connection.java
> +        System.out.println("Greeting: " + response.getToken());
вроде как этот класс не запускается, потому что не указан как main в app

2024-03-13 22:25 UTC, kristinadriam commented on app/build.gradle.kts
> +        exclude(group="org.json", module="json") //provided by Android natively
коммент обязателен?

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/activities/LoginActivity.kt
> +                            user -> Log.d("LoginResponse", user.id.toString());
не нужно ли это в лог инфо?

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/activities/RegisterActivity.kt
> +                            Log.d("RegistrationResponse", registrationResponse.message)
лог инфо х2

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/activities/RegisterActivity.kt
> +                                    Log.d("RegistrationResponse", user.id.toString());
х3

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/viewmodels/AuthViewModel.kt
> +                // TODO: XDDDDDDDDDDDD
🤝

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/viewmodels/AuthViewModel.kt
> +                // TODO: XDDDDDDDDDDDD
🤝

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/etLoginUsername"
гоу id-шники в одном стиле, у меня они в snake_case

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/btnLogin"
да можно и без сокращений, чего уж тут..

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/res/layout/activity_login.xml
> +            android:id="@+id/etLoginPassword"
хорошо б шрифты добавить везде

2024-03-13 22:25 UTC, kristinadriam commented on app/src/main/res/layout/activity_register.xml
> +</LinearLayout>
кажется здесь разумнее еще кнопку обратно к логину добавить + смену активити на логин, вдруг пользователь передумает

2024-03-13 22:25 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/utils/JWTUtils/JWTUtils.java
> +            KeyFactory keyFactory = KeyFactory.getInstance("RSA"); // Use "RSA", "DSA", or "EC" depending on your key type
коммент тут нужен?

2024-03-13 22:25 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/utils/JWTUtils/JWTUtils.java
> +            // Realistically impossible situation
hope so

2024-03-17 12:57 UTC, eyakm1 commented on app/src/main/res/layout/activity_register.xml
> +</LinearLayout>
Есть по системному действию "назад" (свайп налево/нажатие кнопки назад)

2024-03-17 12:59 UTC, eyakm1 commented on app/src/main/AndroidManifest.xml
> +            android:name=".activities.LoginActivity"
:slozhna:

2024-03-18 18:51 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/models/User.kt
> +    val id: Long
это id как в бд id?

2024-03-18 18:51 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/viewmodels/UserViewModel.kt
> +    private val _user = MutableLiveData<User>()
как-то по стилю выбивается, я понимаю, что маркер приватного, но тогда везде так надо делать

2024-03-18 18:54 UTC, eyakm1 commented on app/src/main/java/org/hse/moodactivities/models/User.kt
> +    val id: Long
Да

2024-03-18 18:55 UTC, eyakm1 commented on app/src/main/java/org/hse/moodactivities/viewmodels/UserViewModel.kt
> +    private val _user = MutableLiveData<User>()
Тут скорее маркер на то что это то же самое что и user но приватное мутабельное

2024-03-18 19:15 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/viewmodels/UserViewModel.kt
> +    private val _user = MutableLiveData<User>()
я не буду бухтеть, что из _ надо понять, что метательное, может это и good practice

2024-03-18 19:15 UTC, sssi111 commented on app/src/main/AndroidManifest.xml
> +            android:name=".activities.LoginActivity"
ладно - беклог

2024-03-18 19:16 UTC, sssi111 approved these changes

2024-03-18 19:20 UTC, merged