add calendar
hse-spb-2024-java/MoodActivities pull request #21
Opened 2024-04-23 22:08 UTC by kristinadriam

2024-04-25 22:36 UTC, kristinadriam commented
ревью без учета части, генерирующей рандомные данные, она будет заменена, когда появится бэк

2024-04-25 23:34 UTC, sssi111 reviewed
с поправкой, что это первая итерация - ок, перечитаю после добавления бэка

2024-04-25 23:34 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/adapters/CalendarAdapter.kt
> +        layoutParams.height = (parent.height * 0.166666666).toInt()
а зачем именно 0.166666666

2024-05-04 18:30 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/adapters/CalendarAdapter.kt
> +        layoutParams.height = (parent.height * 0.166666666).toInt()
1 / 0.166666666 ~ 6
строки на 5 недель и 1 строку под надписи дней недели

2024-05-04 18:51 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/adapters/CalendarAdapter.kt
> +        layoutParams.height = (parent.height * 0.166666666).toInt()
надо что-то сделать, чтобы такого хардкора не было

2024-05-04 20:17 UTC, sssi111 requested changes
надо исправить баги, которые обсудили голосом

2024-05-04 20:17 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/responses/FullDayReportResponse.kt
> +            moodEvent.setMoodRate(record.moodsCount)
тут ещё description по идее надо заполнить

2024-05-04 20:17 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/fragments/SummaryOfTheDayFragment.kt
> +        val moodRate= moodEvent.getMoodRate() ?: -1
равно уехало

2024-05-04 20:17 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/fragments/CalendarScreenFragment.kt
> +        view?.findViewById<TextView>(R.id.day_1_text)?.text =
это же моки?

2024-05-04 20:17 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/fragments/CalendarScreenFragment.kt
> +        moodBackground1.setColor(Color.parseColor("#483D8B"))
magic colours 🪄

2024-05-04 20:17 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/activities/CalendarDayActivity.kt
> +                    "",
перед merge надо todo поправить

2024-05-04 20:17 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/activities/CalendarDayActivity.kt
> +            Log.i(
не много ли в info лог сыпется?

2024-05-04 21:22 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/fragments/CalendarScreenFragment.kt
> +        moodBackground1.setColor(Color.parseColor("#483D8B"))
потом уберется, честно

2024-05-04 21:24 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/fragments/CalendarScreenFragment.kt
> +        view?.findViewById<TextView>(R.id.day_1_text)?.text =
да, логика в дальнейшем будет зависеть от ответа сервера

2024-05-04 21:24 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/activities/CalendarDayActivity.kt
> +            Log.i(
добавлю в дебаг

2024-05-04 21:24 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/responses/FullDayReportResponse.kt
> +            moodEvent.setMoodRate(record.moodsCount)
ага, принято

2024-05-06 19:23 UTC, sssi111 approved these changes, later dismissed
часть кода в pr'е написана мной и поэтому ревью не супер правильное, но кроме мелких докапываний про magic colors всё супер

2024-05-06 19:23 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/fragments/CalendarScreenFragment.kt
> +        moodBackground1.setColor(Color.parseColor("#483D8B"))
так,

2024-05-06 19:23 UTC, sssi111 commented on app/src/main/java/org/hse/moodactivities/utils/UiUtils.kt
> +                0 -> Color.parseColor("#483D8B")
some magic 😞

2024-05-06 19:27 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/utils/UiUtils.kt
> +                0 -> Color.parseColor("#483D8B")
потом будет( я же говорила, что цвета не трогаем.....

2024-05-06 19:28 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/adapters/CalendarAdapter.kt
> +        layoutParams.height = (parent.height * 0.166666666).toInt()
fixed

2024-05-06 19:29 UTC, kristinadriam commented on app/src/main/java/org/hse/moodactivities/fragments/CalendarScreenFragment.kt
> +        moodBackground1.setColor(Color.parseColor("#483D8B"))
уберется в темах......

2024-05-06 19:36 UTC, sssi111 approved these changes
помержил с мастером, больше ничего не менял

2024-05-06 19:37 UTC, merged