Settings Handlers
hse-spb-2024-java/MoodActivities pull request #33
Opened 2024-06-13 16:24 UTC by sssi111

2024-06-15 10:51 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/data/entities/postgres/UserProfile.java
> +    public boolean hasGoogle() {
пока без возможности сменить пароль?

2024-06-15 10:51 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/data/entities/postgres/UserProfile.java
> +    public boolean hasGoogle() {
не в гугле, а если регистрация через email

2024-06-15 11:12 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/data/entities/postgres/UserProfile.java
> +    public boolean hasGoogle() {
если чисто наш пароль, то надо обсудить с @eyakm1 не полетит ли токен

2024-06-15 11:14 UTC, eyakm1 requested changes, later dismissed

2024-06-15 11:14 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/services/ProfileService.java
> +        if (userProfile.isEmpty()) {
Вообще это не то чтобы нужно, у нас всегда токен валиден и подписан беком с существующим пользователем, но ладно

2024-06-15 11:14 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/services/ProfileService.java
> +                    .setErrorMessage("can't change password")
да вроде можно....
Как в конструкторе пользователя запилить хешер и всё?

2024-06-15 11:14 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/utils/UserProfileRepository.java
> +    public static boolean saveEntity(UserProfile userProfile) {
очень осуждаю такое

2024-06-15 11:14 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/utils/UserProfileRepository.java
> +        } catch (Exception e) {
В особенности это, хотя бы в лог пиши

2024-06-15 11:25 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/data/entities/postgres/UserProfile.java
> +    private String name;
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

2024-06-18 18:04 UTC, kristinadriam approved these changes

2024-06-18 18:24 UTC, merged