add user entities and mongoClient
hse-spb-2024-java/MoodActivities pull request #6
Opened 2024-02-18 10:24 UTC by sssi111

2024-02-20 14:45 UTC, eyakm1 requested changes
В общем я пока плохо понимаю что у нас должно уехать в монгу, а что в постгрес.

Я очень надеюсь что я сегодня-завтра за это нормально сяду и разберусь.

2024-02-20 14:45 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/backend/MongoDBConnection.java
> +    private static final int MONGO_PORT = 27017;
Это не будет работать в докере.

2024-02-20 14:45 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/backend/entities/User.java
> +public class User {
Половина всего этого должно теоритически уехать в постгрес.

2024-02-20 14:49 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/backend/entities/User.java
> +public class User {
Хотя честно хз.
Всё пока упирается в непонятки с данными.

2024-02-20 14:50 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/backend/entities/User.java
> +public class User {
Вполне может так получится что мы всё в постгресе будем хранить и не париться

2024-02-20 14:50 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/backend/MongoDBConnection.java
> +    private static final int MONGO_PORT = 27017;
Всмысле если бекенд запустить в контейнере

2024-02-21 17:51 UTC, eyakm1 submitted a review, later dismissed
ИМХО директорию `entities` нужно переименовать как-то чтобы было понятно, что это схемы для монги

2024-02-21 17:52 UTC, eyakm1 commented
Остальное выглядит сасно!

2024-02-21 17:53 UTC, eyakm1 commented on backend/src/main/java/org/hse/moodactivities/backend/HelloWorld.java
> +        connection.close();
Нельзя класс для коннекта вынести куда-нибудь в отдельный utility-класс, чтобы не писать каждый раз открытие и закрытие коннекта?

2024-03-02 14:00 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/backend/HelloWorld.java
> +        connection.close();
сделал, чтобы работало через try-with-resources, пока лучше не придумал

2024-03-03 17:58 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/backend/HelloWorld.java
> +        catch (Exception e) {
catch на предыдущую строчку унести

2024-03-03 17:58 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/backend/entities/mongodb/UserDayMeta.java
> +    private double daiScore;
это dayScore?

2024-03-03 17:58 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/backend/entities/mongodb/UserDayMeta.java
> +
чет много пустых строк

2024-03-03 17:58 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/backend/HelloWorld.java
> +        try (MongoDBConnection connection = new MongoDBConnection("localhost", 27017, "user-data")) {
тут можно в константы host/port вынести, как в MongoDBconnection.java. если это «черновик», то можно забить

2024-03-03 17:58 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/backend/utils/MongoDBConnection.java
> +            e.printStackTrace();
мб логирование добавить? или это непринципиально?

2024-03-03 17:58 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/backend/utils/MongoDBConnection.java
> +        try (var find = datastore.find(clazz, document).iterator()) {
clazz имя крутое

2024-03-03 17:58 UTC, kristinadriam commented on backend/src/main/java/org/hse/moodactivities/backend/utils/MongoDBConnection.java
> +}
empty line!!!

2024-03-03 21:07 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/backend/HelloWorld.java
> +        catch (Exception e) {
сделано

2024-03-03 21:08 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/backend/entities/mongodb/UserDayMeta.java
> +    private double daiScore;
dailyScore, поправил

2024-03-03 21:08 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/backend/entities/mongodb/UserDayMeta.java
> +
да, все лишние убрал

2024-03-03 21:09 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/backend/HelloWorld.java
> +        try (MongoDBConnection connection = new MongoDBConnection("localhost", 27017, "user-data")) {
мне немного лень тащить сюда либу для чтения .env, она уже есть в master, и да, это иллюстрация

2024-03-03 21:10 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/backend/utils/MongoDBConnection.java
> +            e.printStackTrace();
легирование добавил, у нас пока slf4j в консоль пишет надо будет в беклог кинуть его настройку

2024-03-03 21:10 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/backend/utils/MongoDBConnection.java
> +        try (var find = datastore.find(clazz, document).iterator()) {
typeClass

2024-03-03 21:11 UTC, sssi111 commented on backend/src/main/java/org/hse/moodactivities/backend/utils/MongoDBConnection.java
> +}
добавил

2024-03-03 21:19 UTC, kristinadriam approved these changes

2024-03-03 21:22 UTC, merged